name = "OptimalPMLTransformations"
uuid = "8e7146f2-eb4f-11e9-33f3-abad4b927b14"
authors = ["jondea <jondea@thedeakin.net>"]
version = "0.1.0"

[deps]
CubicHermiteSpline = "2338ea46-7d83-48cf-b44e-cf8e0b5b9cc1"
Einsum = "b7d42ee7-0b51-5a75-98ca-779d3107e4c0"
FastGaussQuadrature = "442a2c76-b920-505d-bb47-c5924d526838"
HCubature = "19dc6840-f33b-545b-b366-655c7e3ffd49"
InverseHankelFunction = "bec4b5d4-d8c4-11e9-2b25-9be465e100f1"
LinearAlgebra = "37e2e46d-f89d-539d-b4ee-838fcccc9c8e"
OffsetArrays = "6fe1bfb0-de20-5000-8ca7-80f57d26f881"
ProgressMeter = "92933f4c-e287-5a05-a399-4b506db050ca"
SpecialFunctions = "276daf66-3868-5448-9aa4-cd146d93841b"
StaticArrays = "90137ffa-7385-5640-81b9-e52037218182"
Tau = "c544e3c2-d3e5-5802-ac44-44683f340e4a"
